/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "976px",
      xl: "1440px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: {
        oswald: ["Oswald", "sans-serif"],
        opensans: ["Open Sans", "sans-serif"],
      },
      backgroundImage: {
        profileOne: "url('/src/assets/images/wallpapers/wp1.jpeg')",
        profileTwo: "url('/src/assets/images/wallpapers/wp2.png')",
        profileThree: "url('/src/assets/images/wallpapers/wp3.jpeg')",
        profileFour: "url('/src/assets/images/wallpapers/wp4.jpg')",
        profileFive: "url('/src/assets/images/wallpapers/wp5.jpg')",
        profileSix: "url('/src/assets/images/wallpapers/wp6.jpg')",
        profileSeven: "url('/src/assets/images/wallpapers/wp7.jpg')",
        profileEight: "url('/src/assets/images/wallpapers/wp8.jpg')",
        profileNine: "url('/src/assets/images/wallpapers/wp9.jpg')",
        profileTen: "url('/src/assets/images/wallpapers/wp10.jpg')",
        profileEleven: "url('/src/assets/images/wallpapers/wp11.jpg')",
      },
      colors: {
        mentorPrimary: "#3C2D41", // old: 2e1435
        mentorPrimary900: "#2e1435",
        mentorPrimary800: "#3f224b",
        mentorPrimary700: "#482a57",
        mentorPrimary600: "#513361",
        mentorPrimary500: "#573a69",
        mentorPrimary400: "#6c567e",
        mentorPrimary300: "#827394",
        mentorPrimary200: "#a499b3",
        mentorPrimary100: "#c8c1d1",
        mentorPrimary50: "#e9e6ec",
        mentorSecondary: "#eae8e7",
        mentorSecondary900: "#291612",
        mentorSecondary800: "#38221d",
        mentorSecondary700: "#472d25",
        mentorSecondary600: "#56382e",
        mentorSecondary500: "#604034",
        mentorSecondary400: "#775b51",
        mentorSecondary300: "#8d776f",
        mentorSecondary200: "#ad9d98",
        mentorSecondary100: "#cdc4c1",
        mentorSecondary50: "#eae8e7",
        mentorCTA: "#D17B0F",
        mentorCTA900: "#c05607",
        mentorCTA800: "#ca6c0b",
        mentorCTA700: "#D17B0F",
        mentorCTA600: "#d78814",
        mentorCTA500: "#db9219",
        mentorCTA400: "#dfa130",
        mentorCTA300: "#e3b152",
        mentorCTA200: "#ebc782",
        mentorCTA100: "#f2ddb3",
        mentorCTA50: "#faf2e1",
      },
    },
  },
  plugins: [require("flowbite/plugin"), require("tailwind-scrollbar-hide")],
};
